src/objects/Certification__c.object
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CertificationTracking__c.object
<CustomObject>
    <description>The certifications for each employee.</description>
    <fields>
        <fullName>Certification__c</fullName>
        <description>The Certification this record belongs to</description>
        <label>Certification</label>
        <referenceTo>Certification__c</referenceTo>
        <relationshipLabel>CertificationTrackings</relationshipLabel>
        <relationshipName>CertificationTrackings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <description>Employee this record belongs to</description>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>CertificationTrackings</relationshipLabel>
        <relationshipName>CertificationTrackings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CertificationTracking</label>
    <nameField>
        <displayFormat>CTID-{0000}</displayFormat>
        <label>CertificationTracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CertificationTrackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <description>CertTracker Employee</description>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Which Group this employee belongs to</description>
        <inlineHelpText>Select the employee&apos;s group</inlineHelpText>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>EMP-{00000}</displayFormat>
        <label>Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>CertTracker Group</description>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GroupCertification__c.object
<CustomObject>
    <description>A list of all Certifications required for this Group.</description>
    <fields>
        <fullName>Certification__c</fullName>
        <description>The Certification</description>
        <label>Certification</label>
        <referenceTo>Certification__c</referenceTo>
        <relationshipLabel>GroupCertifications</relationshipLabel>
        <relationshipName>GroupCertifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <description>The Group</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>GroupCertifications</relationshipLabel>
        <relationshipName>GroupCertifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GroupCertification</label>
    <nameField>
        <displayFormat>GROUPCERT-{0000}</displayFormat>
        <label>GroupCertification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GroupCertifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NewEmployeeAddTestClass.cls
//---------------------------------------------------------------------------------------------------------
//
//	Module:  NewEmployeeAddTestClass
//
//---------------------------------------------------------------------------------------------------------
//
//  Date	Who		Description
//
// 09/29/14	mjm		Original version - test classes 
//
//---------------------------------------------------------------------------------------------------------
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest (SeeAllData=true)
private class NewEmployeeAddTestClass {

    static testMethod void validateGroupCerts() {
    	Date startDate = Date.newInstance(2014,9,1);
    	
    	System.debug('(validateGroupCerts) enter');
    	
    	System.debug('(validateGroupCerts) creating Certifications');
    	
    	// Create basic set of Groups, Certifications, and GroupCertifications for this test
    	
    	Certification__c tbcert = TestServices.getCert('TB Test', 30, 365);
    	insert tbcert;
    	
    	Certification__c blscert = TestServices.getCert('BLS', 30, 365);
    	insert blscert;
    	
    	System.debug('(validateGroupCerts) creating Group');
    	Group__c grp = TestServices.getGroup('Registered Nurse', 'RN');
    	insert grp;
    	
    	System.debug('(validateGroupCerts) creating GroupCertification tb');
    	GroupCertification__c gc = TestServices.getGroupCert(grp, tbcert);
    	insert gc;

    	System.debug('(validateGroupCerts) creating GroupCertification bls');
    	GroupCertification__c gc2 = TestServices.getGroupCert(grp, blscert);
    	insert gc2;
    	
    	// FOR DEBUG ONLY
    	
    	for (GroupCertification__c gc3 : [SELECT id,Name from GroupCertification__c WHERE id = :gc.Id or id = :gc2.Id]) {
    		System.debug('>>>> found gc: ' + gc3.Name);
    	}
    	// END DEBUG
    	
        Employee__c newEmp = TestServices.getEmployee('McConnell', 'Mitch', grp, startDate);
        insert newEmp;
        
        Employee__c e = [Select Id, Name from Employee__c where Id = :newEmp.Id];
        
        List<CertificationTracking__c> certsList = [Select Id, Name from CertificationTracking__c where Employee__c = :newEmp.Id];
        
        System.debug('Empl Id: ' + e.Id + ', Name: ' + e.Name + ', Count of certs found: ' + certsList.size());
        
        for (CertificationTracking__c c : certsList) {
        	System.debug('Found CT: ' + c.Name);
        }
        
        System.assertEquals(2, certsList.size());
        
    }
}