src/objects/Certification__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether this certification is active.</description>
        <inlineHelpText>Whether this certification is active.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Initial__c</fullName>
        <defaultValue>0</defaultValue>
        <description>f</description>
        <inlineHelpText>The number of days before proof of this certification must be provided after initial hire.</inlineHelpText>
        <label>Initial</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal__c</fullName>
        <description>The number of days before this certification will expire.</description>
        <inlineHelpText>The number of days before this certification will expire.</inlineHelpText>
        <label>Renewal</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <description>CertTracker Employee</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is active</description>
        <inlineHelpText>Check for active employees</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Employee first name</description>
        <inlineHelpText>Employee first name</inlineHelpText>
        <label>First Name</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Which Group this employee belongs to</description>
        <inlineHelpText>Select the employee&apos;s group</inlineHelpText>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Employee last name</description>
        <inlineHelpText>Employee last name</inlineHelpText>
        <label>Last Name</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Employee start date</description>
        <inlineHelpText>Employee start date</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>EMP-{00000}</displayFormat>
        <label>Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>CertTracker Group</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Group is active</description>
        <inlineHelpText>Check to make Group active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_Abbreviation__c</fullName>
        <description>Group Name Abbreviation</description>
        <inlineHelpText>Group name abbreviation</inlineHelpText>
        <label>Abbreviation</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GroupCertification__c.object
<CustomObject>
    <description>A list of all Certifications required for this Group.</description>
    <fields>
        <fullName>Certification__c</fullName>
        <description>The Certification</description>
        <label>Certification</label>
        <referenceTo>Certification__c</referenceTo>
        <relationshipLabel>GroupCertifications</relationshipLabel>
        <relationshipName>GroupCertifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <description>The Group</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>GroupCertifications</relationshipLabel>
        <relationshipName>GroupCertifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GroupCertification</label>
    <nameField>
        <displayFormat>GROUPCERT-{0000}</displayFormat>
        <label>GroupCertification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GroupCertifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestServices.cls
//---------------------------------------------------------------------------------------------------------
//
//	Module:  TestServices
//
//---------------------------------------------------------------------------------------------------------
//
//  Date	Who		Description
//
// 09/29/14	mjm		Original version - helper classes for testing
//
//---------------------------------------------------------------------------------------------------------
@isTest
public with sharing class TestServices {

	public static Certification__c getCert( final String name, final Double initial, final Double renewal) {
		return new Certification__c(name=name, Initial__c=initial,Renewal__c=renewal, Active__c=true);
	}

	public static GroupCertification__c getGroupCert(final Group__c grp, Certification__c cert) {
		return new GroupCertification__c(Group__c=grp.Id, Certification__c=cert.Id);
	}

   public static Group__c getGroup(final String groupname) {
        return new Group__c(Name=groupname,Active__c=true);
    }

   public static Group__c getGroup(final String groupname, final String abbrev) {
        return new Group__c(Name=groupname,Group_Abbreviation__c=abbrev,Active__c=true);
    }

   public static Employee__c getEmployee(final String firstname, 
   										final String lastname, 
   										final Group__c grp,
   										final Date startdate) {
   		
        return new Employee__c(First_Name__c=firstname,Last_Name__c=lastname,Group__c=grp.Id,
             Start_Date__c=startdate);
    }

}