src/objects/Certification__c.object
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <description>CertTracker Employee</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Employee first name</description>
        <inlineHelpText>Employee first name</inlineHelpText>
        <label>First Name</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Which Group this employee belongs to</description>
        <inlineHelpText>Select the employee&apos;s group</inlineHelpText>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>EMP-{00000}</displayFormat>
        <label>Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>CertTracker Group</description>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GroupCertification__c.object
<CustomObject>
    <description>A list of all Certifications required for this Group.</description>
    <fields>
        <fullName>Certification__c</fullName>
        <description>The Certification</description>
        <label>Certification</label>
        <referenceTo>Certification__c</referenceTo>
        <relationshipLabel>GroupCertifications</relationshipLabel>
        <relationshipName>GroupCertifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <description>The Group</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>GroupCertifications</relationshipLabel>
        <relationshipName>GroupCertifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GroupCertification</label>
    <nameField>
        <displayFormat>GROUPCERT-{0000}</displayFormat>
        <label>GroupCertification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GroupCertifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NewEmployeeAdded.cls
public class NewEmployeeAdded{
    public static void AddCertTracking(Employee__c[] employees) {
        for (Employee__c e : employees) {
            System.debug('Found employee: ' + e.First_Name__c);
            System.debug('Group: ' + e.Group__c);
            
            // Get a list of all certifications that belong to the employee's group
            //List<GroupCertification__c> groupCerts = [select id, Certification__c
            //                                          from GroupCertifications
            //                                          where Group__c = e:Group__c];
            // Create a new CertificationTracking record for each of these
            // 
        }
    }
}